CREATE table tbl_Airports(
   IATA_code    VARCHAR(3) NOT NULL PRIMARY KEY
  ,ICAO_code    VARCHAR(4)
  ,airport_name VARCHAR(49) NOT NULL
  ,city_name    VARCHAR(14) NOT NULL
);
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('AGX','VOAT','Agatti Island Airport','Agatti Island');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('AMD','VAAH','Ahmedabad Airport','Ahmedabad');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('AJL','VEAZ','Aizawl Airport','Aizawl');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('AKD','VAAK','Akola Airport','Akola');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXV','VEAN','Along Airport','Along');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('LKO','VILK','Amausi Airport','Lucknow');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('LUH','VILD','Amritsar Airport','Ludhiana');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXB','VEBD','Bagdogra Airport','Bagdogra');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXE','VOML','Bajpe Airport','Mangalore');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXL','VILH','Bakula Rimpoche Airport','Leh');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('RGH','VEBG','Balurghat Airport','Balurghat');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXD','VIAL','Bamrauli Airport','Allahabad');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('SHL','VEBI','Barapani Airport','Shillong');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BEK','VOPN','Bareli Airport','Bareli');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BEP','VOBI','Bellary Airport','Bellary');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BLR','VOBG','Bengaluru International Airport','Bangalore');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BUP','VIBT','Bhatinda Airport','Bhatinda');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BHU','VABV','Bhavnagar Airport','Bhavnagar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BHO','VABP','Bhopal Airport','Bhopal');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BBI','VEBS','Bhubaneswar Airport','Bhubaneswar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BKB','VIBK','Bikaner Airport','Bikaner');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('PAB','VABI','Bilaspur Airport','Bilaspur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXR','VERC','Birsa Munda International Airport','Ranchi');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('GAU','VEGT','Borjhar Airport','Guwahati');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('CBD','VECX','Car Nicobar Airport','Car Nicobar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXC','VICG','Chandigarh Airport','Chandigarh');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('MAA','VOMM','Chennai International Airport','Chennai');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BOM','VABB','Chhatrapati Shivaji International Airport','Mumbai');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXU','VAAU','Chikkalthana Airport','Aurangabad');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('COK','VOCI','Cochin International Airport','Kochi');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('COH','VECO','Cooch Behar Airport','Cooch Behar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('CDP','VOCP','Cuddapah Airport','Cuddapah');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('UDR','VAUD','Dabok Airport','Udaipur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('GOI','VAGO','Dabolim Airport','Goa');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('NMB','VADN','Daman Airport','Daman');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DAE','VEDZ','Daparizo Airport','Daparizo');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DAI',NULL,'Darjeeling Airport','Darjeeling');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DED','VIDN','Dehra Dun Airport','Dehra Dun');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DEP',NULL,'Deparizo Airport','Deparizo');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IDR','VAID','Devi Ahilyabai Holkar Airport','Indore');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DBD','VEDB','Dhanbad Airport','Dhanbad');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DIB','VEMN','Dibrugarh Airport','Dibrugarh');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DMU','VEMR','Dimapur Airport','Dimapur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DIU','VA1P','Diu Airport','Diu');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DHM','VIGG','Gaggal Airport','Dharamsala');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('ISK','VANR','Gandhinagar Airport','Nasik');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('GAY','VEGY','Gaya Airport','Gaya');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('GOP','VEGK','Gorakhpur Airport','Gorakhpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('JGA','VAJM','Govardhanpur Airport','Jamnagar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('GUX','VAGN','Guna Airport','Guna');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('GWL','VIGR','Gwalior Airport','Gwalior');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('HSS','VIHR','Hissar Airport','Hissar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('HBX','VAHB','Hubli Airport','Hubli');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('HYD','VOHY','Hyderabad International Airport','Hyderabad');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('DEL','VIDP','Indira Gandhi International Airport','New Delhi');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('JLR','VAJB','Jabalpur Airport','Jabalpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('JGB',NULL,'Jagdalpur Airport','Jagdalpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('JSA','VIJR','Jaisalmer Airport','Jaisalmer');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('PYB','VEJP','Jeypore Airport','Jeypore');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('JDH','VIJO','Jodhpur Airport','Jodhpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXH','VEKR','Kailashahar Airport','Kailashahar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXQ','VEKM','Kamalpur Airport','Kamalpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXY','VAKE','Kandla Airport','Kandla');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('KNU','VIKA','Kanpur Airport','Kanpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXK','VAKS','Keshod Airport','Keshod');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('HJR','VAKJ','Khajuraho Airport','Khajuraho');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('AGR','VIAG','Kheria Airport','Agra');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXN','VEKW','Khowai Airport','Khowai');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('KLH','VAKP','Kolhapur Airport','Kolhapur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('KTU','VIKO','Kota Airport','Kota');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('CCJ','VOCL','Kozhikode Airport','Kozhikode');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('KUU','VIBR','Kullu Manali Airport','Bhuntar Kullu.');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXS','VEKU','Kumbhirgram Airport','Silchar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXI','VELR','Lilabari Airport','Lilabari');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('PNQ','VAPO','Lohegaon Airport','Pune');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXM','VOMD','Madurai Airport','Madurai');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('LDA','VEMH','Malda Airport','Malda');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('MOH','VEMN','Mohanbari Airport','Mohanbari');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IMF','VEIM','Municipal Airport','Imphal');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('MZA',NULL,'Muzaffarnagar Airport','Muzaffarnagar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('MZU','VEMZ','Muzaffarpur Airport','Muzaffarpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('MYQ','VOMY','Mysore Airport','Mysore');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('NDC','VAND','Nanded Airport','Nanded');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('CCU','VECC','Netaji Subhash Chandra Bose International Airport','Kolkata');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('NVY','VONV','Neyveli Airport','Neyveli');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('OMN',NULL,'Osmanabad Airport','Osmanabad');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('PGH','VIPT','Pantnagar Airport','Pantnagar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXT','VEPG','Pasighat Airport','Pasighat');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXP','VIPK','Pathankot Airport','Pathankot');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('PAT','VEPT','Patna Airport','Patna');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('CJB','VOCB','Peelamedu Airport','Coimbatore');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('PNY','VOPC','Pondicherry Airport','Pondicherry');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('PBD','VAPR','Porbandar Airport','Porbandar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXZ','VOPB','Port Blair Airport','Port Blair');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('PUT',NULL,'Puttaparthi Airport','Puttaparthi');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('RPR','VARP','Raipur Airport','Raipur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('ATQ','VIAR','Raja Sansi Airport','Amritsar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('RJA','VORY','Rajahmundry Airport','Rajahmundry');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('RAJ','VARK','Rajkot Airport','Rajkot');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('RJI',NULL,'Rajouri Airport','Rajouri');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('RMD',NULL,'Ramagundam Airport','Ramagundam');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('RTC','VARG','Ratnagiri Airport','Ratnagiri');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('REW',NULL,'Rewa Airport','Rewa');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('RRK','VERK','Rourkela Airport','Rourkela');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('JRH','VEJT','Rowriah Airport','Jorhat');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BHJ','VABJ','Rudra Mata Airport','Bhuj');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('RUP','VERU','Rupsi Airport','Rupsi');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('SXV','VOSM','Salem Airport','Salem');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('TEZ','VETZ','Salonibari Airport','Tezpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXG','VABM','Sambre Airport','Belgaum');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('JAI','VIJP','Sanganeer Airport','Jaipur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('TNI','VIST','Satna Airport','Satna');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXJ','VIJU','Satwari Airport','Jammu');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('SSE','VASL','Sholapur Airport','Sholapur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('SLV','VISM','Simla Airport','Simla');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXA','VEAT','Singerbhil Airport','Agartala');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('IXW','VEJS','Sonari Airport','Jamshedpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('NAG','VANP','Sonegaon Airport','Nagpur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('SXR','VISR','Srinagar Airport','Srinagar');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('STV','VASU','Surat Airport','Surat');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('TEI','VETJ','Tezu Airport','Tezu');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('TJV','VOTJ','Thanjavur Airport','Thanjavur');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('TRV','VOTV','Thiruvananthapuram International Airport','Trivandrum');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('TIR','VOTP','Tirupati Airport','Tirupati');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('TRZ','VOTR','Trichy Airport','Trichy');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('TCR',NULL,'Tuticorin Airport','Tuticorin');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('BDQ','VABO','Vadodara Airport','Vadodara');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('VNS','VIBN','Varanasi Airport','Varanasi');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('VGA','VOBZ','Vijayawada Airport','Vijayawada');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('VTZ','VEVZ','Vishakhapatnam Airport','Vishakhapatnam');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('WGC','VOWA','Warangal Airport','Warangal');
INSERT INTO tbl_Airports(IATA_code,ICAO_code,airport_name,city_name) VALUES ('ZER','VEZO','Zero Airport','Zero');

select * from tbl_Airports