//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AirlineReservationEntities : DbContext
    {
        public AirlineReservationEntities()
            : base("name=AirlineReservationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_AircraftDetails> tbl_AircraftDetails { get; set; }
        public virtual DbSet<tbl_Airports> tbl_Airports { get; set; }
        public virtual DbSet<tbl_FlightDetails> tbl_FlightDetails { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblBooking> tblBookings { get; set; }
        public virtual DbSet<tblpassenger_table> tblpassenger_table { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblSeat> tblSeats { get; set; }
        public virtual DbSet<tblTicket_table> tblTicket_table { get; set; }
        public virtual DbSet<tblTrip> tblTrips { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    
        public virtual ObjectResult<proc_DetailsConfirmation_Result> proc_DetailsConfirmation(string mBID)
        {
            var mBIDParameter = mBID != null ?
                new ObjectParameter("mBID", mBID) :
                new ObjectParameter("mBID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DetailsConfirmation_Result>("proc_DetailsConfirmation", mBIDParameter);
        }
    
        public virtual int proc_UserRegisteration(string t, string f, string l, Nullable<System.DateTime> dob, string phone, string email, string pass)
        {
            var tParameter = t != null ?
                new ObjectParameter("t", t) :
                new ObjectParameter("t", typeof(string));
    
            var fParameter = f != null ?
                new ObjectParameter("f", f) :
                new ObjectParameter("f", typeof(string));
    
            var lParameter = l != null ?
                new ObjectParameter("l", l) :
                new ObjectParameter("l", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_UserRegisteration", tParameter, fParameter, lParameter, dobParameter, phoneParameter, emailParameter, passParameter);
        }
    
        public virtual ObjectResult<proc_UserLogin_Result> proc_UserLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_UserLogin_Result>("proc_UserLogin");
        }
    
        public virtual ObjectResult<proc_AdminLogin_Result> proc_AdminLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_AdminLogin_Result>("proc_AdminLogin");
        }
    
        public virtual int proc_AddFlight(string td, string dp, string ap, string cabin, string ef, string bf, string ff, string status)
        {
            var tdParameter = td != null ?
                new ObjectParameter("td", td) :
                new ObjectParameter("td", typeof(string));
    
            var dpParameter = dp != null ?
                new ObjectParameter("dp", dp) :
                new ObjectParameter("dp", typeof(string));
    
            var apParameter = ap != null ?
                new ObjectParameter("ap", ap) :
                new ObjectParameter("ap", typeof(string));
    
            var cabinParameter = cabin != null ?
                new ObjectParameter("cabin", cabin) :
                new ObjectParameter("cabin", typeof(string));
    
            var efParameter = ef != null ?
                new ObjectParameter("ef", ef) :
                new ObjectParameter("ef", typeof(string));
    
            var bfParameter = bf != null ?
                new ObjectParameter("bf", bf) :
                new ObjectParameter("bf", typeof(string));
    
            var ffParameter = ff != null ?
                new ObjectParameter("ff", ff) :
                new ObjectParameter("ff", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_AddFlight", tdParameter, dpParameter, apParameter, cabinParameter, efParameter, bfParameter, ffParameter, statusParameter);
        }
    
        public virtual int proc_EditFlight(string fid, string status)
        {
            var fidParameter = fid != null ?
                new ObjectParameter("fid", fid) :
                new ObjectParameter("fid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_EditFlight", fidParameter, statusParameter);
        }
    
        public virtual ObjectResult<proc_ShowFlight_Result> proc_ShowFlight()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_ShowFlight_Result>("proc_ShowFlight");
        }
    
        public virtual ObjectResult<proc_displaypassengers_Result> proc_displaypassengers(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_displaypassengers_Result>("proc_displaypassengers", uidParameter);
        }
    
        public virtual int proc_insertpassengers(string ticketID, string pname, string gender, string seatID, Nullable<int> age)
        {
            var ticketIDParameter = ticketID != null ?
                new ObjectParameter("TicketID", ticketID) :
                new ObjectParameter("TicketID", typeof(string));
    
            var pnameParameter = pname != null ?
                new ObjectParameter("Pname", pname) :
                new ObjectParameter("Pname", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var seatIDParameter = seatID != null ?
                new ObjectParameter("SeatID", seatID) :
                new ObjectParameter("SeatID", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_insertpassengers", ticketIDParameter, pnameParameter, genderParameter, seatIDParameter, ageParameter);
        }
    
        public virtual ObjectResult<proc_DetailsConfirmation1_Result> proc_DetailsConfirmation1(string mBID)
        {
            var mBIDParameter = mBID != null ?
                new ObjectParameter("mBID", mBID) :
                new ObjectParameter("mBID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DetailsConfirmation1_Result>("proc_DetailsConfirmation1", mBIDParameter);
        }
    
        public virtual ObjectResult<proc_UserDetails_Result> proc_UserDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_UserDetails_Result>("proc_UserDetails");
        }
    
        public virtual int proc_UserRegisteration1(string t, string f, string l, Nullable<System.DateTime> dob, string phone, string email, string pass, string sec)
        {
            var tParameter = t != null ?
                new ObjectParameter("t", t) :
                new ObjectParameter("t", typeof(string));
    
            var fParameter = f != null ?
                new ObjectParameter("f", f) :
                new ObjectParameter("f", typeof(string));
    
            var lParameter = l != null ?
                new ObjectParameter("l", l) :
                new ObjectParameter("l", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var secParameter = sec != null ?
                new ObjectParameter("sec", sec) :
                new ObjectParameter("sec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_UserRegisteration1", tParameter, fParameter, lParameter, dobParameter, phoneParameter, emailParameter, passParameter, secParameter);
        }
    
        public virtual ObjectResult<proc_UserDetails1_Result> proc_UserDetails1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_UserDetails1_Result>("proc_UserDetails1");
        }
    
        public virtual ObjectResult<proc_getUserByEmail_Result> proc_getUserByEmail(string email, string sec)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var secParameter = sec != null ?
                new ObjectParameter("sec", sec) :
                new ObjectParameter("sec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getUserByEmail_Result>("proc_getUserByEmail", emailParameter, secParameter);
        }
    
        public virtual int proc_updateUser(string email, string sec)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var secParameter = sec != null ?
                new ObjectParameter("sec", sec) :
                new ObjectParameter("sec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_updateUser", emailParameter, secParameter);
        }
    
        public virtual int proc_updateUser1(string email, string pass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_updateUser1", emailParameter, passParameter);
        }
    
        public virtual int proc_updateUser2(string email, string pass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_updateUser2", emailParameter, passParameter);
        }
    }
}
