//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class projectGladitorEntities : DbContext
    {
        public projectGladitorEntities()
            : base("name=projectGladitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Airports> tbl_Airports { get; set; }
        public virtual DbSet<tbl_AircraftDetails> tbl_AircraftDetails { get; set; }
        public virtual DbSet<tbl_FlightDetails> tbl_FlightDetails { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblBooking> tblBookings { get; set; }
        public virtual DbSet<tblpassenger_table> tblpassenger_table { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblSeat> tblSeats { get; set; }
        public virtual DbSet<tblTicket_table> tblTicket_table { get; set; }
        public virtual DbSet<tblTrip> tblTrips { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    
        public virtual ObjectResult<string> proc_AirportCities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_AirportCities");
        }
    
        public virtual ObjectResult<proc_FlightSelect_Result> proc_FlightSelect(string from, string to, Nullable<System.DateTime> deptdate, Nullable<System.DateTime> returndate, Nullable<int> passengerCount)
        {
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var deptdateParameter = deptdate.HasValue ?
                new ObjectParameter("deptdate", deptdate) :
                new ObjectParameter("deptdate", typeof(System.DateTime));
    
            var returndateParameter = returndate.HasValue ?
                new ObjectParameter("returndate", returndate) :
                new ObjectParameter("returndate", typeof(System.DateTime));
    
            var passengerCountParameter = passengerCount.HasValue ?
                new ObjectParameter("PassengerCount", passengerCount) :
                new ObjectParameter("PassengerCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_FlightSelect_Result>("proc_FlightSelect", fromParameter, toParameter, deptdateParameter, returndateParameter, passengerCountParameter);
        }
    
        public virtual int proc_Booking(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Booking", userIDParameter);
        }
    
        public virtual int proc_TicketBook(string bID, string tripID)
        {
            var bIDParameter = bID != null ?
                new ObjectParameter("BID", bID) :
                new ObjectParameter("BID", typeof(string));
    
            var tripIDParameter = tripID != null ?
                new ObjectParameter("TripID", tripID) :
                new ObjectParameter("TripID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_TicketBook", bIDParameter, tripIDParameter);
        }
    
        public virtual ObjectResult<string> proc_GetBooking(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_GetBooking", userIDParameter);
        }
    
        public virtual ObjectResult<proc_GetBookings_Result> proc_GetBookings(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetBookings_Result>("proc_GetBookings", userIDParameter);
        }
    }
}
